---

- name: Install ceph trusted key for RHEL
  rpm_key:
    state: present
    key: https://download.ceph.com/keys/release.asc
  when: ansible_distribution == 'RedHat'

- name: Configure Ceph $basearch repository
  yum_repository:
    name: "ceph-basearch"
    description: Ceph packages for $basearch
    baseurl: https://download.ceph.com/rpm-luminous/el7/$basearch
    enabled: yes
    priority: 2
    gpgcheck: yes
    gpgkey: https://download.ceph.com/keys/release.asc
    file: ceph-RHEL
  when: ansible_distribution == 'RedHat'

- name: Configure Ceph noarch repository
  yum_repository:
    name: ceph-noarch
    description: Ceph noarch packages
    baseurl: https://download.ceph.com/rpm-luminous/el7/noarch
    enabled: yes
    priority: 2
    gpgcheck: yes
    gpgkey: https://download.ceph.com/keys/release.asc
    file: ceph-RHEL
  when: ansible_distribution == 'RedHat'

- name: Configure Ceph source packages repository
  yum_repository:
    name: ceph-SRPMS
    description: Ceph source packages
    baseurl: https://download.ceph.com/rpm-luminous/el7/SRPMS
    enabled: yes
    priority: 2
    gpgcheck: yes
    gpgkey: https://download.ceph.com/keys/release.asc
    file: ceph-RHEL
  when: ansible_distribution == 'RedHat'

- name: Install ceph-deploy
  yum:
    name: "{{ ceph_deploy_rpm }}"
    state: installed
    allow_downgrade: yes
  when: inventory_hostname in groups['master-server']

...
