######################################################
################# Setup Ceph #########################
######################################################
---

- import_tasks: 00_preflight.yml
  when: inventory_hostname in groups['master-server']

- import_tasks: 05_files.yml
  when: inventory_hostname in groups['master-server']

- import_tasks: 10_install.yml

- import_tasks: 15_setup.yml
  when: inventory_hostname in groups['master-server']

- import_tasks: 20_deploy.yml
  when: inventory_hostname in groups['master-server']

- import_tasks: 25_validate.yml
  when: inventory_hostname in groups['master-server']

...
