######################################################
################# Setup Ceph #########################
######################################################
---

# Quick hack to get ssh keys working with ceph
# - name: SSH Key  
#   copy: 
#     src: "/root/.ssh/{{ item }}"
#     dest: "/root/.ssh"
#     mode: 0400
#   with_items:
#     - "id_rsa"
#     - "id_rsa.pub"
#   when: inventory_hostname in groups['master-servers']

- include_tasks: preflight.yml

- name: Ceph Deploy Block
  block: 
    - include_tasks: files.yml
    - include_tasks: install.yml
    - include_tasks: setup.yml
    - include_tasks: deploy.yml
  when: kube_check_result is defined and kube_check_result.stdout == "" 



