---
- name: Check Provisioner
  include_role:
    name: kubernetes/common
    tasks_from: kube_check
  vars:
    type: "pods"
    namespace: "kube-system"
    resource_name: ""
    label: "app=rbd-provisioner"

- name: Get Ceph Health
  shell: |
    ceph health
  register: ceph_status_result
  ignore_errors: yes
