---

- name: 'Install Docker package'
  yum:
    name: docker
    state: 'installed'

- name: 'Patch outstanding bug'
  file:
    src: /usr/libexec/docker/docker-runc-current
    dest: /usr/libexec/docker/docker-runc
    owner: root
    group: root
    state: link
