######################################################
################# Setup Elasticsearch ################
######################################################
---

- name: "Create directories"
  file:
    group: "{{ es_group }}"
    owner: "{{ es_user }}"
    mode: u+rw,g+rw
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ elastic_dir }}"
    - "{{ elastic_dir }}/data"
    - "{{ elastic_dir }}/config"

- name: Install Templates
  template:
    src: "templates/{{ item }}.yml.j2"
    dest: "{{ elastic_dir }}/{{ item }}.yml"
    group: "{{ es_group }}"
    owner: "{{ es_user }}"
    mode: u+rw,g+rw
  with_items:
    - es-client
    - es-curator-config
    - es-curator_v1beta1
    - es-data-pdb
    - es-data
    - es-discovery-svc
    - es-master-pdb
    - es-master
    - es-svc
    - pv-data
    - pvc-data

- name: Install Config Templates
  template:
    src: "templates/{{ item }}.j2"
    dest: "{{ elastic_config_dir }}/{{ item }}"
    group: "{{ es_group }}"
    owner: "{{ es_user }}"
    mode: u+rw,g+rw
  with_items:
    - elasticsearch.yml
    - jvm.options
    - log4j2.properties

- name: Create Config
  command: 'kubectl --kubeconfig=/etc/kubernetes/admin.conf create configmap {{ elastic_config_map }}-{{ item.0 }} --from-file {{ elastic_config_dir }}/{{ item.1 }}'
  with_indexed_items:
    - elasticsearch.yml
    - jvm.options
    - log4j2.properties

- name: Deploy
  command: 'kubectl --kubeconfig="/etc/kubernetes/admin.conf" create -f {{ elastic_dir }}/{{ item }}.yml'
  with_items:
    - pv-data
    - pvc-data
    - es-master
    - es-discovery-svc
    - es-svc
#    - es-client
#    - es-data

- name: Wait for deployment to finish
  command: 'kubectl --kubeconfig=/etc/kubernetes/admin.conf rollout status deployment/{{ item }}'
  with_items:
    - es-master
#    - es-client
#    - es-data
