######################################################
################# Setup Elasticsearch ################
######################################################
---

- name: "Create directories"
  file:
    group: "{{ es_group }}"
    owner: "{{ es_user }}"
    mode: u+rw,g+rw
    path: "{{ elastic_dir }}"
    state: directory

- name: Install Templates
  template:
    src: "templates/{{ item }}.j2"
    dest: "{{ elastic_dir }}/{{ item }}"
    group: "{{ es_group }}"
    owner: "{{ es_user }}"
    mode: u+rw,g+rw
  with_items:
    - es-client.yml
    - es-curator-config.yml
    - es-curator_v1beta1.yml
    - es-data-pdb.yml
    - es-data.yml
    - es-discovery-svc.yml
    - es-master-pdb.yml
    - es-master.yml
    - es-svc.yml
    - pvc-data.yml
    - elastichq.yml
    - elastichq-svc.yml
    - elasticsearch.yml
    - jvm.options
    - log4j2.properties

- name: Flush Config
  command: 'kubectl delete configmap elastic'
  ignore_errors: true

- name: Create Config
  shell: |
    kubectl create configmap elastic --from-file {{ elastic_dir }}/elasticsearch.yml \
    --from-file {{ elastic_dir }}/jvm.options \
    --from-file {{ elastic_dir }}/log4j2.properties

- name: Flush Deployments
  shell: |
    kubectl delete -f {{ elastic_dir }}/{{ item }}.yml
    while [ $(kubectl get -f {{ elastic_dir }}/{{ item }}.yml | tail -n +2 | wc -l) != '0' ]; do
      echo -n .;
      sleep 1;
    done;
    sleep 5;
  with_items:
    - es-discovery-svc
    - es-svc
    - es-master
    - pvc-data
    - elastichq
    - elastichq-svc
#    - es-client
#    - es-data
  ignore_errors: true

- name: Deploy PVC
  shell: |
    kubectl create -f {{ elastic_dir }}/pvc-data.yml
    while [ $(kubectl get -f {{ elastic_dir }}/pvc-data.yml | tail -n +2 | awk '{ print $2 }') != 'Bound' ]; do
      echo -n .;
      sleep 1;
    done;
    while [ $(kubectl get ep | grep $(kubectl --kubeconfig="{{ kubernetes_conf_file }}" get -f {{ elastic_dir }}/pvc-data.yml | tail -n +2 | awk '{ print $1 }') | wc -l) == '0' ]; do
      echo -n .;
      sleep 1;
    done;

- name: Deploy Pods
  shell: |
    kubectl create -f {{ elastic_dir }}/{{ item }}.yml
    while [ $(kubectl get -f {{ elastic_dir }}/{{ item }}.yml | tail -n +2 | awk '{ print $5}') == '0' ]; do
      echo -n .;
      sleep 1;
    done;
  with_items:
    - es-master
    - elastichq
    #- es-client
    #- es-data

- name: Deploy Services
  command: 'kubectl create -f {{ elastic_dir }}/{{ item }}.yml'
  with_items:
    - es-discovery-svc
    - es-svc
    - elastichq-svc
#    - es-client
#    - es-data
