#######################################################
###################  Kubernetes Setup Nodes ###############
#######################################################
---

- import_tasks: 00_preflight.yml

- name: Install New Node
  import_tasks: 05_install.yml
  when: (kube_reload is defined and kube_reload) or (kube_check_result is defined and kube_check_result.stdout == "")

- name: Label master node with appropriate roles
 include_role:
   name: kubernetes/common
   tasks_from: label_nodes.yml
...
