######################################################
############### Setup Moloch container ###############
######################################################
---

- name: 'Create directories'
  file:
    path: "{{ moloch_dir }}"
    owner: "{{ moloch_user }}"
    group: "{{ moloch_group }}"
    mode: "{{ moloch_dir_mode }}"
    state: directory

- name: 'Copy files'
  copy:
    src: files/config.ini.tmpl
    dest: "{{ moloch_dir }}/config.ini.tmpl"
    owner: root
    group: root
    mode: 0644

- name: 'Copy config files'
  template:
    src: "templates/{{ item }}"
    dest: "{{ moloch_dir }}/{{ item }}"
    mode: "{{ moloch_file_mode }}"
    owner: "{{ moloch_user }}"
    group: "{{ moloch_group }}"
  with_items:
    - auto_init
    - bootstrap.yml
    - deploy.yml
    - svc.yml

- name: "Clean up kube configmap"
  command: "kubectl delete configmap moloch --ignore-not-found"

- name: "Clean up kube for deployment "
  command: "kubectl delete -f {{ moloch_dir }}/{{ item }}.yml --ignore-not-found"
  with_items:
    - bootstrap
    - deploy
    - svc

- name: Get master IP
  shell: |
     sentinel_pod=$(kubectl get pods -l name==redis-sentinel | grep '1/1' | tail -n 1 | awk '{ print $1}')
     master_info=$(kubectl exec -ti $sentinel_pod -- redis-cli -p {{ redis_sentinel_port }} sentinel get-master-addr-by-name mymaster | cut -d'"' -f 2)
     echo "$sentinel_pod"
     echo "$master_info"
  register: master_info

- name: Set Variables
  shell: |
    kubectl exec -ti {{ master_info.stdout_lines.0 }} -- redis-cli -h {{ master_info.stdout_lines.1 }} -p {{ master_info.stdout_lines.2 }} set {{ item.name }} "{{ item.val }}"
  with_items:
    - { name: "/moloch/elastic/url", val: "{{ moloch_elastic_url }}" }

- name: "Wait for deployment to cleanup"
  shell: |
    while [ $(kubectl get pods | grep moloch | wc -l) -gt 0 ]; do
      echo -n .;
      sleep 1;
    done;

- name: "Create kube config"
  shell: |
    kubectl create configmap moloch --from-file {{ moloch_dir }}/config.ini.tmpl

- name: Deploy Bootstrap
  command: kubectl create -f {{ moloch_dir }}/bootstrap.yml

- name: Get Bootstrap pod name
  shell: |
    while [ "$(kubectl get pods | grep moloch-bootstrap | head -n 1 | awk '{ print $2}')" != "1/1" ]; do
      sleep 1;
    done;
    echo -n "$(kubectl get pods | grep moloch-bootstrap | head -n 1 | awk '{ print $1 }')"
  register: moloch_bootstrap_pod

- name: Copy init script
  command: "kubectl cp {{ moloch_dir }}/auto_init {{ moloch_bootstrap_pod.stdout }}:/tmp/auto_init"

- name: Stop moloch services
  shell: "kubectl exec -ti {{ moloch_bootstrap_pod.stdout }} -- /bin/bash -c 'systemctl stop molochcapture molochviewer'"
  ignore_errors: yes

- name: Configure Elasticsearch for moloch
  shell: "kubectl exec -ti {{ moloch_bootstrap_pod.stdout }} -- /usr/bin/expect /tmp/auto_init"
  register: debug_output
  ignore_errors: yes

- name: Debut Outout
  debug: "msg={{ debug_output.stdout }}"

- name: Add user
  command: "kubectl exec -ti {{ moloch_bootstrap_pod.stdout }} -- {{ moloch_path }}/bin/moloch_add_user.sh -c {{ moloch_path }}/etc/config.ini {{ moloch_login }} {{ moloch_login }} {{ moloch_pass }} --admin --webauth"

- name: Remove Bootstrap
  command: kubectl delete -f {{ moloch_dir }}/bootstrap.yml --ignore-not-found

- name: "Deploy moloch"
  command: "kubectl create -f {{ moloch_dir }}/{{ item }}.yml"
  with_items:
    - deploy
    - svc

...
