---

- import_tasks: 05_configure_dnsmasq.yml
  when: inventory_hostname in groups['master-server']

- import_tasks: 10_update_dns.yml
  when: inventory_hostname not in groups['master-server']
  
...
