######################################################
################# Setup Kafka ########################
######################################################
---

- name: "Create Directories"
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: u+rw,g+rw
  with_items:
    - "{{ kafka_dir }}"
    - "{{ kafka_data_dir }}"
    - "{{ zookeeper_dir }}"
    - "{{ zookeeper_data_dir }}"

- name: Install Templates
  template:
    src: "templates/{{ item }}.j2"
    dest: "{{ kafka_dir }}/{{ item }}"
    group: root
    owner: root
    mode: 0644
  with_items:
    - kafka-deploy.yml
    - kafka-svc.yml
    - kafka-dockerfile.yml
    - k-pv-data.yml
    - k-pvc-data.yml
    - z-pv-data.yml
    - z-pvc-data.yml
    - server.properties

#- name: Copy Files
#  copy:
#    src: "files/{{ item[1] }}"
#    dest: "{{ item[0] }}/{{ item[1] }}"
#    group: root
#    owner: root
#    mode: 0644
#  with_nested:
#    - ['{{ kafka_dir }}'] # TODO: Likely unnecessary now: ,'{{ zookeeper_dir }}']
    # TODO: This stuff is now environment variables - ['start-kafka.sh','zoo.cfg']

- name: Create Kafka Config
  command: 'kubectl --kubeconfig="{{ kubernetes_conf_file }}" create configmap {{ kafka_config_map }} --from-file {{ kafka_config_file }}'

- name: Create Zookeeper Config
  command: 'kubectl --kubeconfig="{{ kubernetes_conf_file }}" create configmap {{ zookeeper_config_map }} --from-file {{ zookeeper_config_file }}'

- name: Deploy
  command: 'kubectl --kubeconfig="{{ kubernetes_conf_file }}" create -f {{ kafka_dir }}/{{ item }}.yml'
  with_items:
    - k-pv-data
    - k-pvc-data
    - z-pv-data
    - z-pvc-data
    - kafka-deploy
    - kafka-svc

- name: Wait for deployment to finish
  command: 'kubectl --kubeconfig="{{ kubernetes_conf_file }}" rollout status -f {{ kafka_dir }}/kafka-deploy.yml'

#- name: Create Topics
#  command: >
#    docker exec {{ kafka_container_name }} {{ kafka_install_dir }}/bin/kafka-topics.sh
#      --zookeeper zookeeper:{{ zookeeper_port }}
#      --create
#      --replication-factor 1
#      --topic {{ item }}-raw
#      --partisions 1
#  with_items:
#    - bro
#    - suricata
#    - fsf
