---

# Verify that the kubernetes role has not already run
- name: Check to see if Kubernetes directory is empty
  find:
    paths: "{{ kube_dir }}"
    file_type: file
  register: kubernetelastic_directory

- name: Check for existing directories. If it already exists, we will reinstall.
  import_role:
    name: kubernetes/reset
  when: kubernetelastic_directory.matched | int != 0

...
