#######################################################
###################  Kubernetes Common ###############
#######################################################
---

- name: Check to see if default kube dir exists
  stat:
    path: "/etc/kubernetes"
  register: kdir

- name: Reset Kube
  include_role:
    name: kubernetes/reset
  when: kdir.stat.exists and kdir.stat.isdir

- include_tasks: disable_swap.yml
- include_tasks: kernel_mods.yml
- include_tasks: sysctl.yml
- include_tasks: repo.yml
- include_tasks: install.yml
- include_tasks: services.yml
- include_tasks: env.yml
- include_tasks: cred_dir.yml
- meta: flush_handlers

...
