---
- name: Gluster | Create Service Account
  shell: kubectl create -f {{ gluster_dir }}/heketi-service-account.json
  register: heketi_service_account_result
  
- name: Gluster | Wait for service account
  shell: "kubectl get sa heketi-service-account --no-headers=true | awk '{ print $1 }'"
  register: ds_not_ready
  until: ds_not_ready.stdout=='heketi-service-account'
  retries: 10
  delay: 5
  ignore_errors: yes
  when: heketi_service_account_result.rc == 0