---

- hosts: all
  become: true
  vars_files:
    - /etc/rocknsm/config.yml
  tasks:
  - name: Set authorized keys
    authorized_key:
      user: "{{ ansible_env.SUDO_USER }}"
      state: present
      key: "{{ public_keys }}"

  - name: Enable sudo w/o password
    lineinfile:
     path: /etc/sudoers
     state: present
     regexp: '^{{ ansible_env.SUDO_USER }}\s'
     line: '{{ ansible_env.SUDO_USER }} ALL=(ALL) NOPASSWD: ALL'
