# This file is the playbook which applies to all hosts in the system.

# TODO: Need to determine if we are going to do anything with these.
#  vars:
#    rock_debug: "{{ lookup('env', 'DEBUG') }}"
#    http_proxy: "{{ lookup('env','http_proxy') }}"
#    https_proxy: "{{ lookup('env', 'https_proxy') }}"


  #- name: Debug variables
  #  import_tasks: debug.yml

    ######################################################
    #################  ROCKNSM Scripts  ##################
    ######################################################


  # TODO - see https://github.com/grantcurell/rock/issues/26
  #- name: 'Render rock_status template'
  #  template:
  #    backup: yes
  #    src: rock_status.j2
  #    dest: /usr/local/bin/rock_status
  #    owner: root
  #    group: root
  #    mode: 0755

  #- name: Create rock script symlinks
  #  file:
  #    src: "/usr/local/bin/{{ item.src }}"
  #    dest: "/usr/sbin/{{ item.dest }}"
  #    force: yes
  #    state: link
  #  with_items:
  #    - { src: 'rock_start', dest: 'rock_start' }
  #    - { src: 'rock_stop', dest: 'rock_stop' }
  #    - { src: 'rock_status', dest: 'rock_status' }

  # Training mode / Service mode not needed for AF_PACKET


  # TODO: Need to determine if we're going to do anything with these
  #environment:
  # http_proxy:  "{{ http_proxy }}"
  # https_proxy: "{{ https_proxy }}"
  # HTTP_PROXY:  "{{ http_proxy }}"
  # HTTPS_PROXY: "{{ https_proxy }}"
