---

- hosts: sensors

  pre_tasks:
    - name: Apply override settings, if available
      include_vars: /etc/rocknsm/config.yml

  roles:
    - common_sensor
    - { role: suricata, when: with_suricata }
    - { role: kafka, when: with_kafka }
    - { role: zookeeper, when: with_zookeeper }
    - { role: filebeats, when: with_filebeats }
    - { role: bro, when: with_bro }
