---

all:

  hosts:
    simplerockbuild.simplerock.lan:
      ansible_hostname: 127.0.0.1
      ansible_connection: local
      
  vars:
    rock_online_install: true
    rock_sysctl_file: /etc/sysctl.d/10-ROCK.conf
    rock_data_dir: /data
    rocknsm_dir: /opt/rocknsm
    rock_data_user: root
    rock_data_group: root
    rock_monifs: "{{ ansible_interfaces | difference(['lo', ansible_default_ipv4.interface | default('lo') ])| list }}"
    rock_hostname: "{{ inventory_hostname_short }}"
    rock_fqdn: "{{ inventory_hostname }}"
    rock_mgmt_nets: [ "0.0.0.0/0" ]
    rock_cache_dir: /srv/rocknsm/support
    rocknsm_baseurl: https://packagecloud.io/rocknsm/2/el/7/$basearch
    rocknsm_gpgurl: https://packagecloud.io/rocknsm/2/gpgkey
    rocknsm_local_baseurl: file:///srv/rocknsm
    
    #### Retention Configuration ####
    # Moved all retention configuration variables into their respective roles var/main.yml
    
    #### Docker configuration variables ####
    # Install services with Docker whenever possible vs installing on bare metal.
    containerized_install: true
    
    # Feature options - Don't flip these unless you know what you're doing
    # These control if the service is installed
    
    with_bro: true
    with_docker: true
    with_elasticsearch: true
    with_filebeat: true
    with_fsf: true
    with_harbor: false
    with_kafka: true
    with_kibana: true
    with_logstash: true
    with_nginx: true
    with_portainer: true
    with_pulledpork: true
    with_snort: false
    with_stenographer: true
    with_suricata: true
    with_zookeeper: true
    
    # Feature options - Don't flip these unless you know what you're doing
    # These control if the systemd service is enabled
    
    enable_bro: true
    enable_docker: true
    enable_elasticsearch: true
    enable_filebeat: true
    enable_fsf: false
    enable_kafka: true
    enable_kibana: true
    enable_logstash: true
    enable_nginx: true
    enable_pulledpork: true
    enable_snort: false
    enable_stenographer: false
    enable_suricata: true
    enable_zookeeper: true
    
    rocknsm_package_list:
      - java-1.8.0-openjdk-headless
      - jq
      - GeoIP
      - GeoIP-update
      - tcpreplay
      - tcpdump
      - bats
      - policycoreutils-python
      - htop
      - vim
      - git
      - tmux
      - nmap-ncat
      - logrotate
      - perl-LWP-Protocol-https
      - perl-Sys-Syslog
      - perl-Crypt-SSLeay
      - perl-Archive-Tar
      - easy-rsa
      
    epel_baseurl: http://download.fedoraproject.org/pub/epel/$releasever/$basearch/
    epel_gpgurl:  https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-7
      
  children:
  
    sensors:
      hosts:
        simplerockbuild.simplerock.lan:
          ansible_hostname: 127.0.0.1
          ansible_connection: local
          
      vars:
        bro_cpu: "{{ (ansible_processor_vcpus // 2) if (ansible_processor_vcpus <= 16) else 8 }}"
        pulled_pork_oinkcode: 796f26a2188c4c953ced38ff3ec899d8ae543350
        bro_rockscripts_repo: https://github.com/rocknsm/rock-scripts.git
        pulled_pork_repo: https://github.com/shirkdog/pulledpork.git
        
        #### Retention Configuration ####
        kafka_retention: 168
        suricata_retention: 3
        bro_log_retention: 0
        bro_stats_retention: 0
          
    servers:
      hosts:
        simplerockbuild.simplerock.lan:
          ansible_hostname: 127.0.0.1
          ansible_connection: local
          
      vars:
        es_cluster_name: rocknsm
        es_node_name: "{{ rock_hostname }}"
        es_mem: "{{ (ansible_memtotal_mb // 1024 // 2) if (ansible_memtotal_mb // 1024) < 64 else 31 }}"
        elastic_baseurl: https://artifacts.elastic.co/packages/5.x/yum
        elastic_gpgurl: https://artifacts.elastic.co/GPG-KEY-elasticsearch
        
        #### Retention Configuration ####
        elastic_close_interval: 15
        elastic_delete_interval: 60


  #######################################################
  #####################  Handlers  ######################
  #######################################################
# NOT CURRENTLY IN USE
#  handlers:
#    - name: force sync time
#      command: >
#        chronyc -a 'burst 3/4'; sleep 5; chronyc -a makestep
#
#    - name: configure monitor interfaces
#      shell: >
#        for intf in {{ rock_monifs | join(' ') }}; do
#          /sbin/ifup ${intf};
#        done
#
#    - name: create kafka bro topic
#      command: >
#        /opt/kafka/bin/kafka-topics.sh
#           --zookeeper 127.0.0.1:2181
#           --create
#           --replication-factor 1
#           --topic bro-raw
#           --partitions 1
#
#    - name: create kafka suricata topic
#      command: >
#        /opt/kafka/bin/kafka-topics.sh
#           --zookeeper 127.0.0.1:2181
#           --create
#           --replication-factor 1
#           --topic suricata-raw
#           --partitions 1
#
#    - name: create kafka fsf topic
#      command: >
#        /opt/kafka/bin/kafka-topics.sh
#           --zookeeper 127.0.0.1:2181
#           --create
#           --replication-factor 1
#           --topic fsf-raw
#           --partitions 1
